default_platform(:ios)

platform :ios do
  desc "Build Flutter project"
  lane :build do
    Dir.chdir("..") do
      sh("flutter", "build", "ios", "--no-tree-shake-icons")
    end

    Dir.chdir("../ios") do
      cocoapods(podfile: "./ios/Podfile")
      build_app(scheme: "Runner", configuration: "Release", workspace: "./ios/Runner.xcworkspace", export_method: "development", export_options: {"provisioningProfiles" => {"dev.flutter.VeggieSeasons"=> "BitriseBot-Wildcard"}, "method"=> "development", "signingStyle" => "manual", "signingCertificate"=> "iPhone Developer: Tooling Bot Bitrise"})
    end

    Dir.chdir("../android") do
      build_android_app(task: "assemble", flavor: "Release", project_dir: "./android", gradle_path: "./gradlew")
    end
  end
  
  lane :buildDebug do
    Dir.chdir("..") do
      sh("flutter", "build", "ios", "--debug", "--no-tree-shake-icons")
    end

    Dir.chdir("../ios") do
      cocoapods(podfile: "./ios/Podfile")
      build_app(scheme: "Runner", configuration: "Debug", workspace: "./ios/Runner.xcworkspace", export_method: "development", export_options: {"provisioningProfiles" => {"dev.flutter.VeggieSeasons"=> "BitriseBot-Wildcard"}, "method"=> "development", "signingStyle" => "manual", "signingCertificate"=> "iPhone Developer: Tooling Bot Bitrise"})
    end

    Dir.chdir("../android") do
      build_android_app(task: "assemble", flavor: "Debug", project_dir: "./android", gradle_path: "./gradlew")
    end
  end

  lane :test_fastlane_session do
    sh("bash", "./test_session.sh")
  end
end
